# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "HEJIA_ARTICLE", :id => false, :force => true do |t|
    t.column "ID",                    :integer,  :limit => 19,   :null => false
    t.column "AUTHOR",                :string,   :limit => 510
    t.column "BLOD",                  :integer,  :limit => 1
    t.column "COLOR",                 :string,   :limit => 510
    t.column "COPYRIGHT",             :string,   :limit => 510
    t.column "CREATETIME",            :datetime
    t.column "EXPIRINGDATE",          :datetime
    t.column "FIRSTORDERID",          :integer,  :limit => 19
    t.column "KEYWORD1",              :string,   :limit => 510
    t.column "KEYWORD2",              :string,   :limit => 510
    t.column "LASTMODIFYTIME",        :datetime
    t.column "PUBLISHTIME",           :datetime
    t.column "SECONDORDERID",         :integer,  :limit => 19
    t.column "SOURCE",                :string,   :limit => 510
    t.column "SUMMARY",               :string,   :limit => 4000
    t.column "TITLE",                 :string,   :limit => 510
    t.column "USERID",                :integer,  :limit => 19
    t.column "ZONE",                  :string,   :limit => 510
    t.column "CONTENTID",             :integer,  :limit => 19
    t.column "FIRSTCATEGORY",         :integer,  :limit => 19
    t.column "SECONDCATEGORY",        :integer,  :limit => 19
    t.column "STATE",                 :integer,  :limit => 4
    t.column "IMAGENAME",             :string,   :limit => 510
    t.column "CITYORDERBY",           :integer,  :limit => 19
    t.column "THIRDORDERID",          :integer,  :limit => 19
    t.column "THIRDCATEGORY",         :integer,  :limit => 19
    t.column "PRODUCTFIRSTCATEGORY",  :integer
    t.column "PRODUCTSECONDCATEGORY", :integer
    t.column "PRODUCTTHIRDCATEGORY",  :integer
    t.column "PRODUCTFIRSTORDERID",   :integer
    t.column "PRODUCTSECONDORDERID",  :integer
    t.column "PRODUCTTHIRDORDERID",   :integer
    t.column "TEMPURL",               :string
    t.column "HASHTITLE",             :string
    t.column "ISAUDIT",               :integer,  :limit => 19
    t.column "ISVALID",               :integer,  :limit => 19
    t.column "ISCHOICENESSNUM",       :integer,  :limit => 19
    t.column "BACKREASON",            :string,   :limit => 510
    t.column "ISCHANGED",             :string,   :limit => 510
    t.column "ISCHOICENESS",          :string,   :limit => 510
    t.column "ISCOMMEND",             :string,   :limit => 510
    t.column "ISPASS",                :string,   :limit => 510
    t.column "CHECKPEOPLE",           :integer,  :limit => 19
    t.column "EDITPEOPLE",            :integer,  :limit => 19
    t.column "ADDPEOPLE",             :integer,  :limit => 19
    t.column "ISREADY",               :string,   :limit => 510
    t.column "COMPANYID",             :integer,  :limit => 19
    t.column "CHANGEREASON",          :string,   :limit => 150
    t.column "PV",                    :integer,  :limit => 19
    t.column "DECIDE",                :integer,  :limit => 19
    t.column "PROVINCE1",             :integer,  :limit => 19
    t.column "PROVINCE2",             :integer,  :limit => 19
    t.column "ISDV",                  :string,   :limit => 510
    t.column "ISPROD",                :string,   :limit => 510
    t.column "BRAND_ID",              :integer
    t.column "CHECK_BRAND",           :integer
  end

  add_index "HEJIA_ARTICLE", ["FIRSTCATEGORY"], :name => "index_HEJIA_ARTICLE_FIRSTCATEGORY"
  add_index "HEJIA_ARTICLE", ["SECONDCATEGORY"], :name => "index_HEJIA_ARTICLE_SECONDECATEGORY"
  add_index "HEJIA_ARTICLE", ["THIRDCATEGORY"], :name => "index_HEJIA_ARTICLE_THIRDCATEGORY"
  add_index "HEJIA_ARTICLE", ["ADDPEOPLE"], :name => "index_of_ADDPEOPLE"
  add_index "HEJIA_ARTICLE", ["EDITPEOPLE"], :name => "index_of_EDITPEOPLE"
  add_index "HEJIA_ARTICLE", ["CREATETIME"], :name => "index_of_CREATETIME"
  add_index "HEJIA_ARTICLE", ["STATE"], :name => "index_of_STATE"

  create_table "HEJIA_ARTICLE_ARTICLE", :id => false, :force => true do |t|
    t.column "ARTICLEID", :integer, :limit => 19, :null => false
    t.column "ELT",       :integer, :limit => 19, :null => false
  end

  create_table "HEJIA_ARTICLE_CATEGORY", :id => false, :force => true do |t|
    t.column "ID",           :integer,   :limit => 19,  :null => false
    t.column "CODE",         :string,    :limit => 510
    t.column "HTMLFILE",     :string,    :limit => 510
    t.column "NAME",         :string,    :limit => 510
    t.column "PAGENOS",      :integer,   :limit => 10
    t.column "REMARK",       :string,    :limit => 510
    t.column "TOTALCODE",    :string,    :limit => 510
    t.column "WEBPAGEURL",   :string,    :limit => 510
    t.column "AFFIXADDRESS", :string,    :limit => 510
    t.column "PUBLISHTIME",  :timestamp
    t.column "SHOW",         :string,    :limit => 510
    t.column "STATE",        :string,    :limit => 510
    t.column "TYPE",         :integer,   :limit => 19
    t.column "TYPELEVEL",    :integer,   :limit => 19
    t.column "CHOOSE",       :string,    :limit => 510
    t.column "DOMAIN",       :string,    :limit => 510
    t.column "ORIGINALNAME", :string,    :limit => 510
    t.column "PATH",         :string,    :limit => 510
    t.column "PHOTO",        :string,    :limit => 510
  end

  create_table "HEJIA_ARTICLE_COL", :id => false, :force => true do |t|
    t.column "ID",          :integer,  :limit => 19,  :null => false
    t.column "TYPE",        :integer,  :limit => 19
    t.column "CATEGORY",    :integer,  :limit => 19
    t.column "CREATEDATE",  :datetime
    t.column "TYPELEVEL",   :integer,  :limit => 19
    t.column "MANAGERITEM", :string,   :limit => 510
    t.column "NAME",        :string,   :limit => 510
    t.column "URL",         :string,   :limit => 510
  end

  create_table "HEJIA_ARTICLE_CONTENT", :id => false, :force => true do |t|
    t.column "ID",      :integer, :limit => 19, :null => false
    t.column "CONTENT", :text
  end

  create_table "HEJIA_ARTICLE_PRODUCT", :id => false, :force => true do |t|
    t.column "ARTICLEID", :integer, :limit => 19, :null => false
    t.column "ELT",       :integer, :limit => 19, :null => false
  end

  create_table "HEJIA_ART_PROD_LINK", :id => false, :force => true do |t|
    t.column "ID",          :integer, :limit => 19, :null => false
    t.column "ARTICLEID",   :integer, :limit => 19
    t.column "PRODUCTID",   :integer, :limit => 19
    t.column "PRODUCTNAME", :string
    t.column "PRODUCTURL",  :string
    t.column "MARK",        :string
  end

  create_table "HEJIA_CASE", :id => false, :force => true do |t|
    t.column "ID",              :integer,  :limit => 19,                  :null => false
    t.column "REMARK",          :string,   :limit => 2000
    t.column "CREATEDATE",      :datetime
    t.column "HOSTIMAGE",       :string,   :limit => 510
    t.column "HOSTINFO",        :string,   :limit => 2000
    t.column "INTRODUCE",       :string,   :limit => 2000
    t.column "NAME",            :string,   :limit => 510
    t.column "NEEDPAY",         :integer,  :limit => 1
    t.column "TEMPLATE",        :string,   :limit => 510
    t.column "URL",             :string,   :limit => 510
    t.column "COMPANYID",       :integer,  :limit => 19
    t.column "STATUS",          :string,   :limit => 510
    t.column "EDITORID",        :integer,  :limit => 19
    t.column "LASTMODIFYTIME",  :datetime
    t.column "CONTRACTID",      :integer,  :limit => 19
    t.column "BUILDINGNAME",    :string,   :limit => 510
    t.column "DECOCOST",        :integer,  :limit => 19
    t.column "DESIGNCOST",      :integer,  :limit => 19
    t.column "DESIGNERCOMMENT", :string,   :limit => 4000
    t.column "HOSTCOMMENT",     :string,   :limit => 4000
    t.column "HOUSEAREA",       :integer,  :limit => 19
    t.column "HOUSETYPE",       :string,   :limit => 510
    t.column "DESIGNERID",      :integer,  :limit => 19
    t.column "DESIGNMETHOD",    :string,   :limit => 4000
    t.column "ISNEWCASE",       :integer,  :limit => 1
    t.column "ISGOOD",          :integer,  :limit => 10
    t.column "ISCHANGED",       :string,   :limit => 510
    t.column "ISCHOICENESS",    :string,   :limit => 510
    t.column "ISCOMMEND",       :string,   :limit => 510
    t.column "ISPASS",          :string,   :limit => 510
    t.column "BACKREASON",      :string,   :limit => 510
    t.column "MODIFYID",        :integer,  :limit => 19
    t.column "REPORTERID",      :integer,  :limit => 19
    t.column "MAINPHOTO",       :string,   :limit => 510
    t.column "PRAISINGCOUNT",   :integer,  :limit => 19
    t.column "CRITICISMCOUNT",  :integer,  :limit => 19
    t.column "PROVINCE1",       :integer,  :limit => 19
    t.column "PROVINCE2",       :integer,  :limit => 19
    t.column "DOWNLOADNUM",     :integer,  :limit => 19
    t.column "USERTAGNUM",      :integer,  :limit => 19
    t.column "UPLOADNUM",       :integer,  :limit => 19
    t.column "SHARENUM",        :integer,  :limit => 19
    t.column "LIBANGCOUNT",     :integer,  :limit => 10
    t.column "ISZHUANGHUANG",   :string
    t.column "HUXINGORDER",     :integer,  :limit => 10
    t.column "YUSUANORDER",     :integer,  :limit => 10
    t.column "FENGGEORDER",     :integer,  :limit => 10
    t.column "YONGTUORDER",     :integer,  :limit => 10
    t.column "VIEWCOUNT",       :integer,  :limit => 10
    t.column "CASEUP",          :integer,  :limit => 10,   :default => 0
    t.column "CASEDOWN",        :integer,  :limit => 10,   :default => 0
    t.column "TYPE_ID",         :integer,  :limit => 4
    t.column "ENTITY_ID",       :integer,  :limit => 10
    t.column "STATE",           :integer,                  :default => 1
    t.column "ischeck",         :integer
    t.column "address",         :string
    t.column "matrial",         :string,   :limit => 150
  end

  add_index "HEJIA_CASE", ["ENTITY_ID"], :name => "index_of_ENTITY_ID"
  add_index "HEJIA_CASE", ["COMPANYID"], :name => "index_of_COMPANY_ID"
  add_index "HEJIA_CASE", ["STATUS"], :name => "index_of_status"
  add_index "HEJIA_CASE", ["ISCOMMEND"], :name => "index_of_ISCOMMEND"
  add_index "HEJIA_CASE", ["DESIGNERID"], :name => "index_of_DESIGNERID"

  create_table "HEJIA_CASECOLOREY", :id => false, :force => true do |t|
    t.column "ID",      :integer, :limit => 19, :null => false
    t.column "CASEID",  :integer, :limit => 19
    t.column "COLORID", :integer, :limit => 19
    t.column "ADDRESS", :string
    t.column "NAME",    :string
    t.column "COLOR",   :string
  end

  create_table "HEJIA_CASE_", :id => false, :force => true do |t|
    t.column "ID",              :integer,  :limit => 19,                   :null => false
    t.column "REMARK",          :string,   :limit => 2000
    t.column "CREATEDATE",      :datetime
    t.column "HOSTIMAGE",       :string,   :limit => 510
    t.column "HOSTINFO",        :string,   :limit => 2000
    t.column "INTRODUCE",       :string,   :limit => 2000
    t.column "NAME",            :string,   :limit => 510
    t.column "NEEDPAY",         :integer,  :limit => 1
    t.column "TEMPLATE",        :string,   :limit => 510
    t.column "URL",             :string,   :limit => 510
    t.column "COMPANYID",       :integer,  :limit => 19
    t.column "STATUS",          :string,   :limit => 510
    t.column "EDITORID",        :integer,  :limit => 19
    t.column "LASTMODIFYTIME",  :datetime
    t.column "CONTRACTID",      :integer,  :limit => 19
    t.column "BUILDINGNAME",    :string,   :limit => 510
    t.column "DECOCOST",        :integer,  :limit => 19
    t.column "DESIGNCOST",      :integer,  :limit => 19
    t.column "DESIGNERCOMMENT", :string,   :limit => 4000
    t.column "HOSTCOMMENT",     :string,   :limit => 4000
    t.column "HOUSEAREA",       :integer,  :limit => 19
    t.column "HOUSETYPE",       :string,   :limit => 510
    t.column "DESIGNERID",      :integer,  :limit => 19
    t.column "DESIGNMETHOD",    :string,   :limit => 4000
    t.column "ISNEWCASE",       :integer,  :limit => 1
    t.column "ISGOOD",          :integer,  :limit => 10
    t.column "ISCHANGED",       :string,   :limit => 510
    t.column "ISCHOICENESS",    :string,   :limit => 510
    t.column "ISCOMMEND",       :string,   :limit => 510
    t.column "ISPASS",          :string,   :limit => 510
    t.column "BACKREASON",      :string,   :limit => 510
    t.column "MODIFYID",        :integer,  :limit => 19
    t.column "REPORTERID",      :integer,  :limit => 19
    t.column "MAINPHOTO",       :string,   :limit => 510
    t.column "PRAISINGCOUNT",   :integer,  :limit => 19
    t.column "CRITICISMCOUNT",  :integer,  :limit => 19
    t.column "PROVINCE1",       :integer,  :limit => 19
    t.column "PROVINCE2",       :integer,  :limit => 19
    t.column "DOWNLOADNUM",     :integer,  :limit => 19
    t.column "USERTAGNUM",      :integer,  :limit => 19
    t.column "UPLOADNUM",       :integer,  :limit => 19
    t.column "SHARENUM",        :integer,  :limit => 19
    t.column "LIBANGCOUNT",     :integer,  :limit => 10
    t.column "ISZHUANGHUANG",   :string
    t.column "HUXINGORDER",     :integer,  :limit => 10
    t.column "YUSUANORDER",     :integer,  :limit => 10
    t.column "FENGGEORDER",     :integer,  :limit => 10
    t.column "VIEWCOUNT",       :integer,                  :default => 10
    t.column "YONGTUORDER",     :integer,  :limit => 10
    t.column "CASEUP",          :integer,                  :default => 0
    t.column "CASEDOWN",        :integer,                  :default => 0
  end

  create_table "HEJIA_CASE_ADDITIONALFILE", :id => false, :force => true do |t|
    t.column "ID",       :integer, :limit => 19,  :null => false
    t.column "FILENAME", :string,  :limit => 510
    t.column "TITLE",    :string,  :limit => 510
    t.column "CASEID",   :integer, :limit => 19
  end

  create_table "HEJIA_CASE_CASE", :id => false, :force => true do |t|
    t.column "CASEID", :integer, :limit => 19, :null => false
    t.column "ELT",    :integer, :limit => 19, :null => false
  end

  create_table "HEJIA_CLUES", :id => false, :force => true do |t|
    t.column "Id",         :integer,   :null => false
    t.column "cusname",    :string
    t.column "phone",      :string
    t.column "email",      :string
    t.column "housestyle", :string
    t.column "createdate", :timestamp
    t.column "state",      :integer
    t.column "source",     :integer
    t.column "jiegou",     :string
    t.column "zdate",      :string
    t.column "zxuqiu",     :string
    t.column "fujian",     :string
    t.column "cluedate",   :date
    t.column "nextphone",  :date
  end

  create_table "HEJIA_COMPANY", :id => false, :force => true do |t|
    t.column "ID",                     :integer,                                :null => false
    t.column "CN_NAME",                :string
    t.column "EN_NAME",                :string
    t.column "COMPANY_TYPE",           :integer
    t.column "SECTION",                :string
    t.column "WEB_SITE",               :string
    t.column "ADDRESS",                :string
    t.column "POSTCODE",               :string
    t.column "EMAIL",                  :string
    t.column "FAX",                    :string
    t.column "TEL",                    :string
    t.column "CHECK_COMPANY_NO",       :string
    t.column "CONTACTOR",              :string
    t.column "DESCRIBE",               :text
    t.column "PARENTID",               :integer
    t.column "COMPANY_PP",             :integer
    t.column "COMPANY_SCOPE",          :integer
    t.column "USER_ID",                :integer
    t.column "TOTAL_MONEY",            :integer
    t.column "USED_MONEY",             :integer
    t.column "REMAIN_MONEY",           :integer
    t.column "SERVICE",                :text
    t.column "LOGINNAME",              :string
    t.column "PASSWARD",               :string
    t.column "CONTRACT",               :string,   :limit => 10
    t.column "ENDDATE",                :date
    t.column "CREATEDATE",             :date
    t.column "WEBSTAGE",               :string
    t.column "LINKMAN",                :string
    t.column "ENDBUSINESS",            :string
    t.column "BEGINBUSINESS",          :string
    t.column "COUNTRY",                :string
    t.column "AREA",                   :string,   :limit => 245
    t.column "TYPE",                   :string
    t.column "CODE",                   :string
    t.column "ATTRIBUTE",              :string
    t.column "COMSIZE",                :string
    t.column "STATUS",                 :string
    t.column "CONTRACTID",             :integer
    t.column "HASORDERMANAGERFEATURE", :integer
    t.column "HASCHATMANAGERFEATURE",  :integer
    t.column "ONLINETIME",             :integer
    t.column "SUBCOMPANYS",            :string
    t.column "COMPANYLOGO",            :string
    t.column "COMPANYTYPE",            :string
    t.column "SI_NAME",                :string,   :limit => 510
    t.column "ADVERTISEID",            :integer
    t.column "COMPANYTAGS",            :string
    t.column "ADVERTISE",              :string
    t.column "EXAMINEADDRESS",         :string
    t.column "STARCLASS",              :integer,  :limit => 10
    t.column "SALETITLE",              :string,   :limit => 510
    t.column "MOBELTELEPHONE",         :string,   :limit => 510
    t.column "HEADPIC",                :string,   :limit => 510
    t.column "ORDERID",                :integer,  :limit => 10
    t.column "NOTE",                   :string,   :limit => 510
    t.column "BRAND",                  :string,   :limit => 510
    t.column "HOTSALE",                :string,   :limit => 510
    t.column "SCOPE",                  :string,   :limit => 510
    t.column "PRICELISTINFO",          :text
    t.column "PHONE",                  :string,   :limit => 510
    t.column "ANSWERPHONE1",           :string,   :limit => 510
    t.column "ANSWERPHONE2",           :string,   :limit => 510
    t.column "ANSWERPHONE3",           :string,   :limit => 510
    t.column "PHONECUT",               :string,   :limit => 510
    t.column "SALESMAN",               :string,   :limit => 510
    t.column "COMPANYCODE",            :string,   :limit => 510
    t.column "SERVICECLOSETIME",       :string,   :limit => 510
    t.column "SERVICESTARTTIME",       :string,   :limit => 510
    t.column "COMPANYSHORTNAME",       :string,   :limit => 510
    t.column "RANDOMPV",               :integer
    t.column "THROUGH",                :string,   :limit => 510
    t.column "NEEDRECHECKED",          :integer,  :limit => 10
    t.column "SALESMANID",             :integer
    t.column "PAGETYPE",               :string,   :limit => 510
    t.column "SPECIAL",                :integer
    t.column "QQ",                     :string,   :limit => 510
    t.column "MSN",                    :string,   :limit => 510
    t.column "MARKETID",               :integer
    t.column "SERVICELEVEL",           :string,   :limit => 510
    t.column "GUILDID",                :string,   :limit => 510
    t.column "PEIHELEVEL",             :string,   :limit => 510
    t.column "OPBEGINTIME",            :datetime
    t.column "OPENDTIME",              :datetime
    t.column "ERRORDESCRIPTION",       :string,   :limit => 510
    t.column "MERCHANT",               :string,   :limit => 510
    t.column "STRGONGDI",              :text
    t.column "ASKNAME",                :string,   :limit => 510
    t.column "ASKURL",                 :string,   :limit => 510
    t.column "JIANGTANGURL",           :string,   :limit => 510
    t.column "COMPANYPAY",             :integer
    t.column "NEWZHUANGXIUGONGSI",     :string
    t.column "MOBANPATH",              :string
    t.column "COMPANYCREATEDATE",      :string
    t.column "POINT",                  :string
    t.column "PRICEMETOD",             :string
    t.column "ZHUANGXIUMETHOD",        :string
    t.column "GOODSTYLE",              :string
    t.column "TEMPLATEPATH",           :string
    t.column "COMPANYCITY",            :integer
    t.column "COMPANYAREA",            :integer
    t.column "COMPANYSPECIAL",         :string
    t.column "DIQU",                   :string
    t.column "PRODUCTDEALNUM",         :integer,  :limit => 10
    t.column "DESIGNABILITY",          :integer
    t.column "BUGETREQNSONALITY",      :integer
    t.column "CONSTRACTQUALITY",       :integer
    t.column "AFTERSERVICE",           :integer
    t.column "TELCOUNT",               :integer
    t.column "PPZMD",                  :integer,  :limit => 10
    t.column "JGCXD",                  :integer,  :limit => 10
    t.column "SHFUD",                  :integer,  :limit => 10
    t.column "primary_vantag",         :integer
    t.column "primary_style",          :integer
    t.column "confirm",                :integer,                 :default => 0
  end

  create_table "HEJIA_COMPANY_INFO", :id => false, :force => true do |t|
    t.column "ID",          :integer, :limit => 19, :null => false
    t.column "INFO",        :text
    t.column "NEWACTIVITY", :text
    t.column "STATUS",      :integer, :limit => 10
  end

  create_table "HEJIA_COMPANY_PHOTO", :id => false, :force => true do |t|
    t.column "ID",            :integer, :limit => 19,  :null => false
    t.column "CONTENT",       :string,  :limit => 510
    t.column "ENTITYID",      :integer, :limit => 19
    t.column "ENTITYTYPE",    :string,  :limit => 510
    t.column "IMAGENAME",     :string,  :limit => 510
    t.column "STATE",         :string,  :limit => 510
    t.column "DEMONSTRATION", :string,  :limit => 510
    t.column "PHOTOTYPE",     :string,  :limit => 510
    t.column "ORDERNUMBER",   :integer, :limit => 19
    t.column "URL",           :string,  :limit => 510
  end

  create_table "HEJIA_COMPANY_SERVICE", :id => false, :force => true do |t|
    t.column "ID",      :integer, :limit => 19, :null => false
    t.column "SERVICE", :text
  end

  create_table "HEJIA_COMPANY_SHOP", :id => false, :force => true do |t|
    t.column "ID",          :integer, :limit => 19,  :null => false
    t.column "SHOPADD",     :string,  :limit => 510
    t.column "SHOPCONTACT", :string,  :limit => 510
    t.column "SHOPFAX",     :string,  :limit => 510
    t.column "SHOPNAME",    :string,  :limit => 510
    t.column "SHOPTEL",     :string,  :limit => 510
    t.column "COMPANYID",   :integer, :limit => 19
    t.column "ADDRESS",     :string,  :limit => 510
  end

  create_table "HEJIA_COMPANY_copy", :id => false, :force => true do |t|
    t.column "ID",                     :integer,                 :null => false
    t.column "CN_NAME",                :string
    t.column "EN_NAME",                :string
    t.column "COMPANY_TYPE",           :integer
    t.column "SECTION",                :string
    t.column "WEB_SITE",               :string
    t.column "ADDRESS",                :string
    t.column "POSTCODE",               :string
    t.column "EMAIL",                  :string
    t.column "FAX",                    :string
    t.column "TEL",                    :string
    t.column "CHECK_COMPANY_NO",       :string
    t.column "CONTACTOR",              :string
    t.column "DESCRIBE",               :text
    t.column "PARENTID",               :integer
    t.column "COMPANY_PP",             :integer
    t.column "COMPANY_SCOPE",          :integer
    t.column "USER_ID",                :integer
    t.column "TOTAL_MONEY",            :integer
    t.column "USED_MONEY",             :integer
    t.column "REMAIN_MONEY",           :integer
    t.column "SERVICE",                :text
    t.column "LOGINNAME",              :string
    t.column "PASSWARD",               :string
    t.column "CONTRACT",               :string,   :limit => 10
    t.column "ENDDATE",                :date
    t.column "CREATEDATE",             :date
    t.column "WEBSTAGE",               :string
    t.column "LINKMAN",                :string
    t.column "ENDBUSINESS",            :string
    t.column "BEGINBUSINESS",          :string
    t.column "COUNTRY",                :string
    t.column "AREA",                   :string,   :limit => 245
    t.column "TYPE",                   :string
    t.column "CODE",                   :string
    t.column "ATTRIBUTE",              :string
    t.column "COMSIZE",                :string
    t.column "STATUS",                 :string
    t.column "CONTRACTID",             :integer
    t.column "HASORDERMANAGERFEATURE", :integer
    t.column "HASCHATMANAGERFEATURE",  :integer
    t.column "ONLINETIME",             :integer
    t.column "SUBCOMPANYS",            :string
    t.column "COMPANYLOGO",            :string
    t.column "COMPANYTYPE",            :string
    t.column "SI_NAME",                :string,   :limit => 510
    t.column "ADVERTISEID",            :integer
    t.column "COMPANYTAGS",            :string
    t.column "ADVERTISE",              :string
    t.column "EXAMINEADDRESS",         :string
    t.column "STARCLASS",              :integer,  :limit => 10
    t.column "SALETITLE",              :string,   :limit => 510
    t.column "MOBELTELEPHONE",         :string,   :limit => 510
    t.column "HEADPIC",                :string,   :limit => 510
    t.column "ORDERID",                :integer,  :limit => 10
    t.column "NOTE",                   :string,   :limit => 510
    t.column "BRAND",                  :string,   :limit => 510
    t.column "HOTSALE",                :string,   :limit => 510
    t.column "SCOPE",                  :string,   :limit => 510
    t.column "PRICELISTINFO",          :text
    t.column "PHONE",                  :string,   :limit => 510
    t.column "ANSWERPHONE1",           :string,   :limit => 510
    t.column "ANSWERPHONE2",           :string,   :limit => 510
    t.column "ANSWERPHONE3",           :string,   :limit => 510
    t.column "PHONECUT",               :string,   :limit => 510
    t.column "SALESMAN",               :string,   :limit => 510
    t.column "COMPANYCODE",            :string,   :limit => 510
    t.column "SERVICECLOSETIME",       :string,   :limit => 510
    t.column "SERVICESTARTTIME",       :string,   :limit => 510
    t.column "COMPANYSHORTNAME",       :string,   :limit => 510
    t.column "RANDOMPV",               :integer
    t.column "THROUGH",                :string,   :limit => 510
    t.column "NEEDRECHECKED",          :integer,  :limit => 10
    t.column "SALESMANID",             :integer
    t.column "PAGETYPE",               :string,   :limit => 510
    t.column "SPECIAL",                :integer
    t.column "QQ",                     :string,   :limit => 510
    t.column "MSN",                    :string,   :limit => 510
    t.column "MARKETID",               :integer
    t.column "SERVICELEVEL",           :string,   :limit => 510
    t.column "GUILDID",                :string,   :limit => 510
    t.column "PEIHELEVEL",             :string,   :limit => 510
    t.column "OPBEGINTIME",            :datetime
    t.column "OPENDTIME",              :datetime
    t.column "ERRORDESCRIPTION",       :string,   :limit => 510
    t.column "MERCHANT",               :string,   :limit => 510
    t.column "STRGONGDI",              :text
    t.column "ASKNAME",                :string,   :limit => 510
    t.column "ASKURL",                 :string,   :limit => 510
    t.column "JIANGTANGURL",           :string,   :limit => 510
    t.column "COMPANYPAY",             :integer
    t.column "NEWZHUANGXIUGONGSI",     :string
    t.column "MOBANPATH",              :string
    t.column "COMPANYCREATEDATE",      :string
    t.column "POINT",                  :string
    t.column "PRICEMETOD",             :string
    t.column "ZHUANGXIUMETHOD",        :string
    t.column "GOODSTYLE",              :string
    t.column "TEMPLATEPATH",           :string
    t.column "COMPANYCITY",            :integer
    t.column "COMPANYAREA",            :integer
    t.column "COMPANYSPECIAL",         :string
    t.column "DIQU",                   :string
    t.column "PRODUCTDEALNUM",         :integer,  :limit => 10
    t.column "DESIGNABILITY",          :integer
    t.column "BUGETREQNSONALITY",      :integer
    t.column "CONSTRACTQUALITY",       :integer
    t.column "AFTERSERVICE",           :integer
    t.column "TELCOUNT",               :integer
    t.column "PPZMD",                  :integer,  :limit => 10
    t.column "JGCXD",                  :integer,  :limit => 10
    t.column "SHFUD",                  :integer,  :limit => 10
    t.column "primary_vantag",         :integer
    t.column "primary_style",          :integer
  end

  create_table "HEJIA_DECOIMAGE", :id => false, :force => true do |t|
    t.column "ID",         :integer, :limit => 19,   :null => false
    t.column "IMAGENAME",  :string,  :limit => 510
    t.column "INTRODUCE",  :string,  :limit => 2000
    t.column "MAIN",       :integer, :limit => 1
    t.column "SLIDE",      :integer, :limit => 1
    t.column "CASEID",     :integer, :limit => 19
    t.column "FLOWSTATUS", :string,  :limit => 510
    t.column "USERID",     :integer, :limit => 19
  end

  create_table "HEJIA_DECOIMAGE_copy", :id => false, :force => true do |t|
    t.column "ID",         :integer, :limit => 19,   :null => false
    t.column "IMAGENAME",  :string,  :limit => 510
    t.column "INTRODUCE",  :string,  :limit => 2000
    t.column "MAIN",       :integer, :limit => 1
    t.column "SLIDE",      :integer, :limit => 1
    t.column "CASEID",     :integer, :limit => 19
    t.column "FLOWSTATUS", :string,  :limit => 510
    t.column "USERID",     :integer, :limit => 19
  end

  add_index "HEJIA_DECOIMAGE_copy", ["CASEID"], :name => "index_of_CASEID"

  create_table "HEJIA_DESIGNERMODEL", :id => false, :force => true do |t|
    t.column "ID",        :integer, :limit => 19,   :null => false
    t.column "COMPANY",   :integer, :limit => 19
    t.column "DESAGE",    :string,  :limit => 510
    t.column "DESFEE",    :string,  :limit => 510
    t.column "DESNAME",   :string,  :limit => 510
    t.column "DESRESUME", :string,  :limit => 510
    t.column "DESSCHOOL", :string,  :limit => 510
    t.column "DESTEL",    :string,  :limit => 510
    t.column "PICURL",    :string,  :limit => 510
    t.column "WORKAGE",   :string,  :limit => 510
    t.column "DESSTYLE",  :string,  :limit => 510
    t.column "STATUS",    :string,  :limit => 510
    t.column "GLORY",     :string,  :limit => 1000
    t.column "GRADE",     :string
    t.column "POSITION",  :string
  end

  create_table "HEJIA_DESIGNERMODEL_", :id => false, :force => true do |t|
    t.column "ID",        :integer, :limit => 19,  :null => false
    t.column "COMPANY",   :integer, :limit => 19
    t.column "DESAGE",    :string,  :limit => 510
    t.column "DESFEE",    :string,  :limit => 510
    t.column "DESNAME",   :string,  :limit => 510
    t.column "DESRESUME", :string,  :limit => 510
    t.column "DESSCHOOL", :string,  :limit => 510
    t.column "DESTEL",    :string,  :limit => 510
    t.column "PICURL",    :string,  :limit => 510
    t.column "WORKAGE",   :string,  :limit => 510
    t.column "DESSTYLE",  :string,  :limit => 510
    t.column "STATUS",    :string,  :limit => 510
  end

  create_table "HEJIA_EDITOR", :id => false, :force => true do |t|
    t.column "ID",               :integer,  :limit => 19,  :null => false
    t.column "ARTICLEEDITOR",    :integer,  :limit => 10
    t.column "ARTICLEREPRINT",   :integer,  :limit => 10
    t.column "ARTICLETOPIC",     :integer,  :limit => 10
    t.column "COMPANY",          :integer,  :limit => 10
    t.column "PRODUCT",          :integer,  :limit => 10
    t.column "QUESTION",         :integer,  :limit => 10
    t.column "REVISIONANSWER",   :integer,  :limit => 10
    t.column "REVISIONQUESTION", :integer,  :limit => 10
    t.column "TUKUTAGS",         :integer,  :limit => 10
    t.column "TUKUTOPIC",        :integer,  :limit => 10
    t.column "COMMUNICATION",    :integer,  :limit => 10
    t.column "EDITORNAME",       :string,   :limit => 510
    t.column "ORGANIZATION",     :integer,  :limit => 10
    t.column "USERBBSID",        :integer,  :limit => 19
    t.column "WORKRESULT",       :integer,  :limit => 10
    t.column "VIDEO",            :integer,  :limit => 10
    t.column "ARTICLEPV",        :integer,  :limit => 10
    t.column "COMPANYPV",        :integer,  :limit => 10
    t.column "CREATETIME",       :datetime
    t.column "ENDTIME",          :datetime
    t.column "PRODUCTPV",        :integer,  :limit => 10
    t.column "QUESTIONPV",       :integer,  :limit => 10
    t.column "TUKUPV",           :integer,  :limit => 10
    t.column "VIDEOPV",          :integer,  :limit => 10
    t.column "TYPE",             :string,   :limit => 510
    t.column "LEADERID",         :integer,  :limit => 19
    t.column "LEADERNAME",       :string,   :limit => 510
    t.column "BLOG",             :integer,  :limit => 10
    t.column "BLOGPV",           :integer,  :limit => 10
  end

  create_table "HEJIA_FACTORY_COMPANY", :id => false, :force => true do |t|
    t.column "ID",          :integer,  :limit => 19,  :null => false
    t.column "COMPANYID",   :integer,  :limit => 19
    t.column "CREATETIME",  :datetime
    t.column "DESCRIPTION", :string,   :limit => 510
    t.column "ENDENABLE",   :datetime
    t.column "FANGXING",    :string,   :limit => 510
    t.column "NAME",        :string,   :limit => 510
    t.column "PROVINCE1",   :integer,  :limit => 19
    t.column "PROVINCE2",   :integer,  :limit => 19
    t.column "STARTENABLE", :datetime
    t.column "PAIXUMA",     :integer,  :limit => 19
    t.column "CONDITION",   :string,   :limit => 510
    t.column "STYLE",       :string,   :limit => 510
    t.column "MONEY",       :string,   :limit => 510
  end

  create_table "HEJIA_FACTORY_COMPANY_", :id => false, :force => true do |t|
    t.column "ID",          :integer,  :limit => 19,  :null => false
    t.column "COMPANYID",   :integer,  :limit => 19
    t.column "CREATETIME",  :datetime
    t.column "DESCRIPTION", :string,   :limit => 510
    t.column "ENDENABLE",   :datetime
    t.column "FANGXING",    :string,   :limit => 510
    t.column "NAME",        :string,   :limit => 510
    t.column "PROVINCE1",   :integer,  :limit => 19
    t.column "PROVINCE2",   :integer,  :limit => 19
    t.column "STARTENABLE", :datetime
    t.column "PAIXUMA",     :integer,  :limit => 19
    t.column "CONDITION",   :string,   :limit => 510
    t.column "STYLE",       :string,   :limit => 510
    t.column "MONEY",       :string,   :limit => 510
  end

  create_table "HEJIA_GROUP", :id => false, :force => true do |t|
    t.column "ID",        :integer, :limit => 19,  :null => false
    t.column "DESCN",     :string,  :limit => 510
    t.column "NAME",      :string,  :limit => 510
    t.column "PARENT_ID", :integer, :limit => 19
  end

  create_table "HEJIA_HOUSEMODEL", :id => false, :force => true do |t|
    t.column "ID",        :integer, :limit => 19,   :null => false
    t.column "IMAGENAME", :string,  :limit => 510
    t.column "INTRODUCE", :string,  :limit => 2000
    t.column "CASEID",    :integer, :limit => 19
    t.column "IMAGETYPE", :string,  :limit => 510
  end

  create_table "HEJIA_HOUSEMODEL_", :id => false, :force => true do |t|
    t.column "ID",        :integer, :limit => 19,   :null => false
    t.column "IMAGENAME", :string,  :limit => 510
    t.column "INTRODUCE", :string,  :limit => 2000
    t.column "CASEID",    :integer, :limit => 19
    t.column "IMAGETYPE", :string,  :limit => 510
  end

  create_table "HEJIA_IMGCOLOR", :id => false, :force => true do |t|
    t.column "ID",                :integer, :limit => 19, :null => false
    t.column "NAME",              :string
    t.column "IMAGECOLORCONTENT", :string
    t.column "COLOR",             :string
    t.column "STATUS",            :string
    t.column "COUNT",             :integer, :limit => 19
  end

  create_table "HEJIA_MATERIAL", :id => false, :force => true do |t|
    t.column "ID",         :integer, :limit => 19,  :null => false
    t.column "ITEM",       :string,  :limit => 510
    t.column "PRICE",      :string,  :limit => 510
    t.column "CASEID",     :integer, :limit => 19
    t.column "BRAND",      :string,  :limit => 510
    t.column "FEELING",    :string,  :limit => 510
    t.column "BRANDURL",   :string,  :limit => 510
    t.column "ITEMURL",    :string,  :limit => 510
    t.column "THEDECOURL", :string,  :limit => 510
  end

  create_table "HEJIA_MATERIAL_", :id => false, :force => true do |t|
    t.column "ID",         :integer, :limit => 19,  :null => false
    t.column "ITEM",       :string,  :limit => 510
    t.column "PRICE",      :string,  :limit => 510
    t.column "CASEID",     :integer, :limit => 19
    t.column "BRAND",      :string,  :limit => 510
    t.column "FEELING",    :string,  :limit => 510
    t.column "BRANDURL",   :string,  :limit => 510
    t.column "ITEMURL",    :string,  :limit => 510
    t.column "THEDECOURL", :string,  :limit => 510
  end

  create_table "HEJIA_PUBLISH_CHANNEL", :id => false, :force => true do |t|
    t.column "ID",            :integer,  :limit => 19,   :null => false
    t.column "CATEGORY",      :string,   :limit => 510
    t.column "DESCRIPTION",   :string,   :limit => 4000
    t.column "LASTBUILDDATE", :datetime
    t.column "PUBDATE",       :datetime
    t.column "TITLE",         :string,   :limit => 512
    t.column "TITLEURL",      :string,   :limit => 512
    t.column "TYPE",          :integer,  :limit => 19
    t.column "TYPELEVEL",     :integer,  :limit => 19
  end

  create_table "HEJIA_RESOURCE", :id => false, :force => true do |t|
    t.column "ID",        :integer, :limit => 19,  :null => false
    t.column "DESCN",     :string,  :limit => 510
    t.column "NAME",      :string,  :limit => 510
    t.column "RESSTRING", :string,  :limit => 510
    t.column "RESTYPE",   :string,  :limit => 510
    t.column "STATE",     :string,  :limit => 510
  end

  create_table "HEJIA_ROLE", :id => false, :force => true do |t|
    t.column "ID",    :integer, :limit => 19,  :null => false
    t.column "DESCN", :string,  :limit => 510
    t.column "NAME",  :string,  :limit => 510
  end

  create_table "HEJIA_ROLERESOURCE", :id => false, :force => true do |t|
    t.column "ID",      :integer, :limit => 19,  :null => false
    t.column "NAME",    :string,  :limit => 510
    t.column "ROLESQL", :string,  :limit => 510
    t.column "TYPEID",  :integer, :limit => 19
  end

  create_table "HEJIA_ROLERESOURCE_LINK", :id => false, :force => true do |t|
    t.column "ID",             :integer, :limit => 19, :null => false
    t.column "ROLERESOURCEID", :integer, :limit => 19
    t.column "USERID",         :integer, :limit => 19
  end

  create_table "HEJIA_TAG", :id => false, :force => true do |t|
    t.column "TAGID",       :integer,  :limit => 19,                   :null => false
    t.column "TAGFATHERID", :integer,  :limit => 19,                   :null => false
    t.column "TAGNAME",     :string,   :limit => 510,  :default => "", :null => false
    t.column "TAGVALUE",    :string,   :limit => 4000
    t.column "TAGICON",     :string,   :limit => 510
    t.column "TAGURL",      :string,   :limit => 510
    t.column "TAGTAXIS",    :integer,  :limit => 19
    t.column "TAGESTATE",   :string,   :limit => 510,  :default => "", :null => false
    t.column "TAGDATE",     :datetime
    t.column "TAGCODE",     :string,   :limit => 510
    t.column "TAGTYPE",     :string,   :limit => 510
    t.column "BIDDING",     :integer
    t.column "SPELL",       :string
    t.column "TEMPURL",     :string
    t.column "VERSION",     :string
    t.column "TAGCOMMENT",  :string
    t.column "ISIMPORTANT", :boolean
  end

  add_index "HEJIA_TAG", ["TAGNAME"], :name => "index_TAGNAME"

  create_table "HEJIA_TAGLINK", :id => false, :force => true do |t|
    t.column "TAGLINKID", :integer, :limit => 19,                  :null => false
    t.column "TAGID1",    :string,  :limit => 510, :default => "", :null => false
    t.column "TAGID2",    :string,  :limit => 510, :default => "", :null => false
  end

  create_table "HEJIA_TAG_ENTITY_LINK", :id => false, :force => true do |t|
    t.column "ID",              :integer,  :limit => 19,                                                :null => false
    t.column "CREATEDATE",      :datetime
    t.column "ENTITYID",        :integer,  :limit => 19,                                                :null => false
    t.column "PRICE",           :decimal,                 :precision => 20, :scale => 5
    t.column "PRIORITY",        :string,   :limit => 510
    t.column "TAGID",           :integer,  :limit => 19,                                                :null => false
    t.column "STATUS",          :integer,  :limit => 10,                                 :default => 1
    t.column "LINKTYPE",        :string
    t.column "STATE",           :integer
    t.column "FOREORDAINPRICE", :decimal,                 :precision => 19, :scale => 2
  end

  add_index "HEJIA_TAG_ENTITY_LINK", ["ENTITYID"], :name => "ENTITYID"
  add_index "HEJIA_TAG_ENTITY_LINK", ["ENTITYID"], :name => "INDEX_ENTITYID"
  add_index "HEJIA_TAG_ENTITY_LINK", ["TAGID"], :name => "INDEX_TAGID"
  add_index "HEJIA_TAG_ENTITY_LINK", ["LINKTYPE"], :name => "index_of_LINKTYPE"

  create_table "HEJIA_TAG_ENTITY_LINK_copy", :id => false, :force => true do |t|
    t.column "ID",              :integer,  :limit => 19,                                                :null => false
    t.column "CREATEDATE",      :datetime
    t.column "ENTITYID",        :integer,  :limit => 19,                                                :null => false
    t.column "PRICE",           :decimal,                 :precision => 20, :scale => 5
    t.column "PRIORITY",        :string,   :limit => 510
    t.column "TAGID",           :integer,  :limit => 19,                                                :null => false
    t.column "STATUS",          :integer,  :limit => 10,                                 :default => 1
    t.column "LINKTYPE",        :string
    t.column "STATE",           :integer
    t.column "FOREORDAINPRICE", :decimal,                 :precision => 19, :scale => 2
  end

  add_index "HEJIA_TAG_ENTITY_LINK_copy", ["ENTITYID", "TAGID", "LINKTYPE"], :name => "index_of_ENTITYID"

  create_table "HEJIA_USER_ACTIVITY", :id => false, :force => true do |t|
    t.column "ID",               :integer,  :limit => 19,  :null => false
    t.column "ACTIVITYID",       :integer,  :limit => 19
    t.column "ADDRESS",          :string,   :limit => 510
    t.column "AGE",              :string,   :limit => 510
    t.column "BUDGET",           :string,   :limit => 510
    t.column "EMAIL",            :string,   :limit => 510
    t.column "EXPECTHOUSEMODEL", :string,   :limit => 510
    t.column "EXPECTPERSONNUM",  :integer,  :limit => 19
    t.column "HOUSEADDRESS",     :string,   :limit => 510
    t.column "HOUSEAREA",        :string,   :limit => 510
    t.column "HOUSEMODEL",       :string,   :limit => 510
    t.column "HOUSEMODELIMAGE",  :string,   :limit => 510
    t.column "HOUSESTYLE",       :string,   :limit => 510
    t.column "HOUSETIME",        :string,   :limit => 510
    t.column "HOUSETYPE",        :string,   :limit => 510
    t.column "MOBILE",           :string,   :limit => 510
    t.column "MSN",              :string,   :limit => 510
    t.column "NAME",             :string,   :limit => 510
    t.column "OCCUPATION",       :string,   :limit => 510
    t.column "PHONE",            :string,   :limit => 510
    t.column "POSTCODE",         :string,   :limit => 510
    t.column "QQ",               :string,   :limit => 510
    t.column "REMARK",           :string,   :limit => 510
    t.column "CREATETIME",       :datetime
    t.column "SEX",              :string,   :limit => 510
    t.column "USERFAVORTAG",     :string,   :limit => 510
    t.column "AREA",             :string,   :limit => 510
    t.column "SALARY",           :string,   :limit => 510
  end

  create_table "HEJIA_USER_BBS", :id => false, :force => true do |t|
    t.column "USERBBSID",             :integer,  :limit => 19,                   :null => false
    t.column "USERNAME",              :string,   :limit => 64,   :default => "", :null => false
    t.column "BBSID",                 :string,   :limit => 510,  :default => "", :null => false
    t.column "USERBBSADDRESS",        :string,   :limit => 510
    t.column "USERBBSCODE",           :string,   :limit => 510
    t.column "USERBBSEMAIL",          :string,   :limit => 510
    t.column "USERBBSNAME",           :string,   :limit => 510
    t.column "USERBBSREADME",         :string,   :limit => 2048
    t.column "USERBBSSEX",            :string,   :limit => 510
    t.column "USERBBSTEL",            :string,   :limit => 510
    t.column "USERBBSROLE",           :string,   :limit => 510
    t.column "ROLEADMIN",             :string
    t.column "HEADIMG",               :string
    t.column "MSN",                   :string
    t.column "QQ",                    :string
    t.column "USERBBSMOBELTELEPHONE", :string
    t.column "CLIENTID",              :integer,  :limit => 19
    t.column "PASSWORD",              :string,   :limit => 510
    t.column "CITY",                  :string,   :limit => 510
    t.column "AREA",                  :string,   :limit => 510
    t.column "REPAIRENJOY",           :string,   :limit => 510
    t.column "REPAIRTYPE",            :string,   :limit => 510
    t.column "ISACTIVATE",            :integer,  :limit => 1
    t.column "USERTYPE",              :integer,  :limit => 10
    t.column "REPAIRTIME",            :string,   :limit => 510
    t.column "USERVALIDAT",           :string,   :limit => 510
    t.column "ISDEL",                 :integer,  :limit => 1
    t.column "CREATTIME",             :datetime
    t.column "LOGINIP",               :string,   :limit => 510
    t.column "LOGINDATE",             :datetime
    t.column "USERSPASSWORD",         :string,   :limit => 510
    t.column "USERSLOGINNUM",         :integer,  :limit => 19
    t.column "ISWESKIT",              :integer,  :limit => 10
    t.column "AGE",                   :integer,  :limit => 19
    t.column "BUDGET",                :string,   :limit => 510
    t.column "EXPECTHOUSEADDRESS",    :string,   :limit => 510
    t.column "EXPECTHOUSEMODEL",      :string,   :limit => 510
    t.column "EXPECTPRODUCT",         :string,   :limit => 510
    t.column "HOUSEADDRESS",          :string,   :limit => 510
    t.column "HOUSEAREA",             :string,   :limit => 510
    t.column "HOUSEMODEL",            :string,   :limit => 510
    t.column "HOUSEMODELIMAGE",       :string,   :limit => 510
    t.column "HOUSESTYLE",            :string,   :limit => 510
    t.column "OCCUPATION",            :string,   :limit => 510
    t.column "REMARK",                :string,   :limit => 510
    t.column "EXPECTPERSONNUM",       :integer,  :limit => 19
    t.column "OFTENUSEDEMAIL",        :string,   :limit => 510
    t.column "USERFAVORTAG",          :string,   :limit => 510
    t.column "ANJIA",                 :integer,  :limit => 1
    t.column "POINT",                 :integer,  :limit => 19
    t.column "MENBER",                :integer,  :limit => 10
    t.column "URL",                   :string
    t.column "MEMBERCODE",            :string
    t.column "MEMBERSTARTTIME",       :datetime
    t.column "MEMBERENDTIME",         :date
    t.column "ACTIVEMEMBER",          :integer,  :limit => 10
    t.column "MEMBERADD",             :string
    t.column "deco_id",               :integer,                  :default => 0,  :null => false
    t.column "credits",               :integer,                  :default => 0
    t.column "ask_expert",            :integer,  :limit => 4,    :default => 0,  :null => false
    t.column "ischeck",               :integer
    t.column "user_id",               :integer
  end

  add_index "HEJIA_USER_BBS", ["USERNAME"], :name => "index_of_USERNAME", :unique => true
  add_index "HEJIA_USER_BBS", ["ask_expert"], :name => "ask_expert"

  create_table "HEJIA_USER_ROLE", :id => false, :force => true do |t|
    t.column "ROLE_ID", :integer, :limit => 19, :null => false
    t.column "USER_ID", :integer, :limit => 19, :null => false
  end

  create_table "HEJIA_USER_TAG", :id => false, :force => true do |t|
    t.column "TAGID",       :integer,  :limit => 19,  :null => false
    t.column "TAGCODE",     :string,   :limit => 510
    t.column "TAGDATE",     :datetime
    t.column "TAGSTATE",    :string,   :limit => 510
    t.column "TAGFATHERID", :integer,  :limit => 19
    t.column "TAGNAME",     :string,   :limit => 510
    t.column "TAGTYPE",     :string,   :limit => 510
    t.column "TYPEID",      :integer,  :limit => 19
    t.column "USERBBSID",   :integer,  :limit => 19
  end

  create_table "admin_logs", :force => true do |t|
  end

  create_table "archive", :id => false, :force => true do |t|
    t.column "ar_namespace",  :integer,                :default => 0,                                                          :null => false
    t.column "ar_title",      :binary,  :limit => 255, :default => "",                                                         :null => false
    t.column "ar_text",       :binary,                 :default => "",                                                         :null => false
    t.column "ar_comment",    :binary,                 :default => "",                                                         :null => false
    t.column "ar_user",       :integer, :limit => 10,  :default => 0,                                                          :null => false
    t.column "ar_user_text",  :binary,  :limit => 255, :default => "",                                                         :null => false
    t.column "ar_timestamp",  :binary,  :limit => 14,  :default => "\000\000\000\000\000\000\000\000\000\000\000\000\000\000", :null => false
    t.column "ar_minor_edit", :integer, :limit => 4,   :default => 0,                                                          :null => false
    t.column "ar_flags",      :binary,                 :default => "",                                                         :null => false
    t.column "ar_rev_id",     :integer, :limit => 10
    t.column "ar_text_id",    :integer, :limit => 10
    t.column "ar_deleted",    :integer, :limit => 3,   :default => 0,                                                          :null => false
    t.column "ar_len",        :integer, :limit => 10
    t.column "ar_page_id",    :integer, :limit => 10
    t.column "ar_parent_id",  :integer, :limit => 10
  end

  add_index "archive", ["ar_namespace", "ar_title", "ar_timestamp"], :name => "name_title_timestamp"
  add_index "archive", ["ar_user_text", "ar_timestamp"], :name => "usertext_timestamp"

  create_table "article_images", :force => true do |t|
    t.column "product_id",   :integer
    t.column "parent_id",    :integer
    t.column "title",        :string
    t.column "filename",     :string
    t.column "content_type", :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "is_primary",   :boolean,   :default => false
    t.column "createdate",   :timestamp
  end

  add_index "article_images", ["product_id"], :name => "index_product_id"
  add_index "article_images", ["is_primary"], :name => "index_is_primary"

  create_table "article_info_images", :force => true do |t|
    t.column "name",             :string
    t.column "description",      :string,   :limit => 1000
    t.column "imagepath",        :string
    t.column "article_infos_id", :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "image_url",        :string
  end

  add_index "article_info_images", ["article_infos_id"], :name => "index_of_article_infos_id"

  create_table "article_infos", :force => true do |t|
    t.column "title",           :string,                 :default => "", :null => false
    t.column "content",         :text
    t.column "image",           :string,   :limit => 45
    t.column "article_urls_id", :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "added_status",    :integer,  :limit => 4,  :default => 0
  end

  add_index "article_infos", ["article_urls_id"], :name => "index_of_article_urls_id"
  add_index "article_infos", ["image"], :name => "index_of_image"
  add_index "article_infos", ["title"], :name => "index_article_infos_title"
  add_index "article_infos", ["created_at"], :name => "index_article_infos_created_at"

# Could not dump table "article_infos_copy" because of following ActiveRecord::StatementInvalid
#   Interrupt: : SHOW KEYS FROM article_infos_copy

  create_table "article_sites", :force => true do |t|
    t.column "url",        :string,                 :default => "", :null => false
    t.column "name",       :string,   :limit => 45
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "article_urls", :force => true do |t|
    t.column "url",              :string,                :default => "", :null => false
    t.column "is_fetched",       :integer,  :limit => 4, :default => 0
    t.column "article_sites_id", :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  add_index "article_urls", ["is_fetched"], :name => "index_is_fetched"
  add_index "article_urls", ["url"], :name => "index_of_url"

  create_table "ask_authorized_users", :force => true do |t|
    t.column "user_id",           :integer
    t.column "authority_type_id", :integer
    t.column "is_valid",          :integer,  :default => 1, :null => false
    t.column "expired_at",        :datetime
    t.column "editor_id",         :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "ask_blocked_ips", :force => true do |t|
    t.column "ip",         :string,   :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "ask_blocked_ips", ["id"], :name => "index_blocked_ip_id", :unique => true
  add_index "ask_blocked_ips", ["ip"], :name => "index_blocked_ip_ip"

  create_table "ask_blog_albums", :force => true do |t|
    t.column "user_id",           :integer
    t.column "album_name",        :string
    t.column "album_description", :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "ask_blog_categories", :force => true do |t|
    t.column "user_id",              :integer
    t.column "category_name",        :string
    t.column "category_description", :string
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
  end

  create_table "ask_blog_choices", :force => true do |t|
    t.column "sort_id",       :integer
    t.column "user_id",       :integer
    t.column "topic_type_id", :integer,  :default => 4
    t.column "topic_id",      :integer
    t.column "title",         :string
    t.column "url",           :string
    t.column "image_title",   :string
    t.column "image_url",     :string
    t.column "is_valid",      :integer,  :default => 1, :null => false
    t.column "order_number",  :integer
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_blog_configs", :force => true do |t|
    t.column "user_id",          :integer
    t.column "blog_name",        :string
    t.column "blog_description", :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "ask_blog_sorts", :force => true do |t|
    t.column "sort_name",        :string
    t.column "sort_description", :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "ask_blog_states", :force => true do |t|
    t.column "user_id",    :integer
    t.column "is_active",  :integer,  :default => 1, :null => false
    t.column "is_edit",    :integer,  :default => 1, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_blog_statistics", :force => true do |t|
    t.column "user_id",    :integer
    t.column "source_url", :string
    t.column "visitor_id", :integer
    t.column "visitor_ip", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_blog_topic_posts", :force => true do |t|
    t.column "blog_topic_id", :integer
    t.column "user_id",       :integer
    t.column "guest_email",   :string
    t.column "ip",            :string
    t.column "content",       :text
    t.column "is_delete",     :integer,  :default => 0, :null => false
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_blog_topics", :force => true do |t|
    t.column "area_id",      :integer
    t.column "user_id",      :integer
    t.column "ip",           :string
    t.column "category_id",  :integer
    t.column "tag_id",       :integer
    t.column "subject",      :string
    t.column "description",  :text
    t.column "view_counter", :integer,  :default => 1, :null => false
    t.column "post_counter", :integer,  :default => 1, :null => false
    t.column "is_draft",     :integer,  :default => 0, :null => false
    t.column "is_top",       :integer,  :default => 0, :null => false
    t.column "is_use",       :integer,  :default => 0, :null => false
    t.column "is_delete",    :integer,  :default => 0, :null => false
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  add_index "ask_blog_topics", ["user_id"], :name => "index_ask_blog_topics_user_id"
  add_index "ask_blog_topics", ["category_id"], :name => "index_ask_blog_topics_category_id"

  create_table "ask_company_comments", :force => true do |t|
    t.column "guest_name",         :string
    t.column "company_id",         :integer
    t.column "user_id",            :integer
    t.column "design_ability",     :integer
    t.column "buget_reasonality",  :integer
    t.column "construct_quality",  :integer
    t.column "after_source",       :integer
    t.column "recommend_designer", :string
    t.column "description",        :string
    t.column "ip",                 :string
    t.column "is_delete",          :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
  end

  create_table "ask_editor_choices", :force => true do |t|
    t.column "area_id",       :integer,                 :null => false
    t.column "type_id",       :integer
    t.column "topic_type_id", :integer
    t.column "topic_id",      :integer
    t.column "title",         :string
    t.column "url",           :string
    t.column "image_title",   :string
    t.column "image_url",     :string
    t.column "order_number",  :integer
    t.column "is_valid",      :integer,  :default => 1, :null => false
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_editor_operations", :force => true do |t|
    t.column "editor_id",     :integer
    t.column "project_id",    :integer
    t.column "operation_id",  :integer
    t.column "operation_url", :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_forum_admins", :force => true do |t|
    t.column "forum_tag_id", :integer
    t.column "admin_id",     :integer
    t.column "is_delete",    :integer,  :default => 0, :null => false
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_forum_choices", :force => true do |t|
    t.column "area_id",       :integer,                 :null => false
    t.column "type_id",       :integer
    t.column "topic_type_id", :integer
    t.column "topic_id",      :integer
    t.column "user_id",       :integer
    t.column "title",         :string
    t.column "url",           :string
    t.column "image_title",   :string
    t.column "image_url",     :string
    t.column "order_number",  :integer
    t.column "is_valid",      :integer,  :default => 1, :null => false
    t.column "editor_id",     :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "description",   :string
  end

  create_table "ask_forum_tags", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "alias_id",   :integer
    t.column "parent_id",  :integer
    t.column "tag_level",  :integer
    t.column "tag_order",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "ask_forum_tags", ["id"], :name => "index_forum_tag_id", :unique => true
  add_index "ask_forum_tags", ["name"], :name => "index_forum_tag_name"

  create_table "ask_forum_topic_posts", :force => true do |t|
    t.column "forum_topic_id", :integer,                 :null => false
    t.column "user_id",        :integer
    t.column "guest_email",    :string
    t.column "ip",             :string
    t.column "content",        :text
    t.column "is_delete",      :integer,  :default => 0, :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "method",         :integer,                 :null => false
    t.column "editor_id",      :integer
    t.column "level_id",       :integer
  end

  add_index "ask_forum_topic_posts", ["id"], :name => "index_forum_topic_post_id", :unique => true
  add_index "ask_forum_topic_posts", ["created_at"], :name => "index_forum_topic_post_created_at"
  add_index "ask_forum_topic_posts", ["forum_topic_id"], :name => "index_forum_topic_post_topic_id"
  add_index "ask_forum_topic_posts", ["level_id"], :name => "level_id"
  add_index "ask_forum_topic_posts", ["user_id"], :name => "index_forum_topic_post_user_id"

  create_table "ask_forum_topics", :force => true do |t|
    t.column "area_id",         :integer,                  :null => false
    t.column "user_id",         :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "tag_id",          :integer
    t.column "subject",         :string,   :default => "", :null => false
    t.column "method",          :integer,                  :null => false
    t.column "description",     :text
    t.column "reference",       :string
    t.column "is_delete",       :integer,  :default => 0,  :null => false
    t.column "is_close",        :integer,  :default => 0,  :null => false
    t.column "post_counter",    :integer,  :default => 1,  :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "latest_reply_at", :datetime
    t.column "editor_id",       :integer
    t.column "is_distribute",   :integer,  :default => 0
    t.column "source",          :string
    t.column "source_id",       :string
    t.column "view_counter",    :integer,  :default => 1,  :null => false
    t.column "is_top",          :integer,  :default => 0,  :null => false
    t.column "is_good",         :integer,  :default => 0,  :null => false
    t.column "level_id",        :integer
    t.column "zhidao_topic_id", :integer
    t.column "reality_view",    :integer,  :default => 0,  :null => false
  end

  add_index "ask_forum_topics", ["id"], :name => "index_forum_topic_id", :unique => true
  add_index "ask_forum_topics", ["subject"], :name => "index_forum_topic_subject"
  add_index "ask_forum_topics", ["tag_id"], :name => "index_forum_topic_tag_id"
  add_index "ask_forum_topics", ["level_id"], :name => "index_forum_topic_level_id"
  add_index "ask_forum_topics", ["user_id"], :name => "index_forum_topic_user_id"
  add_index "ask_forum_topics", ["is_top"], :name => "index_forum_topic_is_top"
  add_index "ask_forum_topics", ["area_id"], :name => "index_forum_area_id"
  add_index "ask_forum_topics", ["is_delete"], :name => "index_forum_is_delete"
  add_index "ask_forum_topics", ["zhidao_topic_id"], :name => "zhidao_topic_id"
  add_index "ask_forum_topics", ["is_good"], :name => "is_good"

  create_table "ask_forum_userlevel", :force => true do |t|
    t.column "level", :string
  end

  add_index "ask_forum_userlevel", ["level"], :name => "level"

  create_table "ask_hejia_companies", :force => true do |t|
    t.column "cn_name",                   :string
    t.column "address",                   :string
    t.column "tel",                       :string
    t.column "linkman",                   :string
    t.column "web_stage",                 :string
    t.column "country",                   :string
    t.column "area",                      :string
    t.column "type_id",                   :string
    t.column "guild_id",                  :string
    t.column "has_order_manager_feature", :integer,  :default => 0
    t.column "has_chat_manager_feature",  :integer,  :default => 0
    t.column "create_date",               :datetime
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "editor_id",                 :integer
    t.column "post_counter",              :integer,  :default => 1, :null => false
    t.column "view_counter",              :integer,  :default => 1, :null => false
    t.column "is_delete",                 :integer,  :default => 0, :null => false
    t.column "method",                    :integer,  :default => 1, :null => false
    t.column "area_id",                   :integer,  :default => 1
    t.column "user_id",                   :integer
    t.column "description",               :string
  end

  create_table "ask_hejia_company_posts", :force => true do |t|
    t.column "hejia_company_id", :integer,                 :null => false
    t.column "user_id",          :integer
    t.column "guest_email",      :string
    t.column "ip",               :string
    t.column "content",          :text
    t.column "is_delete",        :integer,  :default => 0, :null => false
    t.column "method",           :integer,                 :null => false
    t.column "editor_id",        :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "ask_operations", :force => true do |t|
    t.column "name",        :string,   :default => "", :null => false
    t.column "description", :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_score_orders", :force => true do |t|
    t.column "operation_id",    :integer,  :null => false
    t.column "operation_score", :integer,  :null => false
    t.column "version",         :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_search_keywords", :force => true do |t|
    t.column "area_id",    :integer,                  :null => false
    t.column "type_id",    :integer,                  :null => false
    t.column "keyword",    :string,   :default => "", :null => false
    t.column "user_id",    :integer
    t.column "ip",         :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_statistics", :force => true do |t|
    t.column "app_controller", :string
    t.column "app_action",     :string
    t.column "visit_url",      :string
    t.column "visitor_id",     :integer
    t.column "visitor_ip",     :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_tag_links", :force => true do |t|
    t.column "start_id",    :integer,  :null => false
    t.column "end_id",      :integer,  :null => false
    t.column "link_weight", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_taolun_tags", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "alias_id",   :integer
    t.column "parent_id",  :integer
    t.column "tag_level",  :integer
    t.column "tag_order",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_taolun_topic_posts", :force => true do |t|
    t.column "taolun_topic_id", :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "content",         :text
    t.column "is_delete",       :integer,  :default => 0, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "method",          :integer,                 :null => false
    t.column "editor_id",       :integer
  end

  create_table "ask_taolun_topics", :force => true do |t|
    t.column "area_id",       :integer,                  :null => false
    t.column "user_id",       :integer
    t.column "guest_email",   :string
    t.column "ip",            :string
    t.column "tag_id",        :integer
    t.column "subject",       :string,   :default => "", :null => false
    t.column "method",        :integer,                  :null => false
    t.column "description",   :text
    t.column "reference",     :string
    t.column "is_delete",     :integer,  :default => 0,  :null => false
    t.column "is_close",      :integer,  :default => 0,  :null => false
    t.column "post_counter",  :integer,  :default => 1,  :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
    t.column "is_distribute", :integer,  :default => 0
    t.column "source",        :string
    t.column "source_id",     :integer
    t.column "view_counter",  :integer,  :default => 1,  :null => false
    t.column "is_top",        :integer,  :default => 0,  :null => false
  end

  create_table "ask_tieba_topic_posts", :force => true do |t|
    t.column "tieba_topic_id", :integer,                 :null => false
    t.column "user_id",        :integer
    t.column "content",        :text
    t.column "is_delete",      :integer,  :default => 0, :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_tieba_topics", :force => true do |t|
    t.column "area_id",      :integer,                  :null => false
    t.column "tieba_id",     :integer,                  :null => false
    t.column "user_id",      :integer,                  :null => false
    t.column "tag_id",       :integer,                  :null => false
    t.column "subject",      :string,   :default => "", :null => false
    t.column "method",       :integer,                  :null => false
    t.column "is_delete",    :integer,  :default => 0,  :null => false
    t.column "post_counter", :integer,  :default => 1,  :null => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_tiebas", :force => true do |t|
    t.column "area_id",      :integer,                  :null => false
    t.column "user_id",      :integer,                  :null => false
    t.column "name",         :string,   :default => "", :null => false
    t.column "company_name", :string,   :default => "", :null => false
    t.column "description",  :string
    t.column "sign",         :string
    t.column "icon_url",     :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_topic_reads", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "topic_type_id", :integer,  :null => false
    t.column "topic_id",      :integer,  :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_topic_subscriptions", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "topic_type_id", :integer,  :null => false
    t.column "topic_id",      :integer,  :null => false
    t.column "guest_email",   :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "ask_topic_tag_urls", :force => true do |t|
    t.column "tag_id",         :integer,  :null => false
    t.column "topic_url",      :string
    t.column "topic_url_type", :string
    t.column "topic_id",       :integer
    t.column "topic_type_id",  :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  create_table "ask_topic_user_tags", :force => true do |t|
    t.column "user_tag_id",   :integer
    t.column "topic_type_id", :integer
    t.column "topic_id",      :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "editor_id",     :integer
  end

  create_table "ask_user_infos", :force => true do |t|
    t.column "user_id",    :integer,  :null => false
    t.column "nickname",   :string
    t.column "sex",        :string
    t.column "sign",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_user_messages", :force => true do |t|
    t.column "send_user_id",    :integer
    t.column "receive_user_id", :integer
    t.column "content",         :string
    t.column "state",           :integer,  :default => 0, :null => false
    t.column "is_read",         :integer,  :default => 0, :null => false
    t.column "parent_id",       :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_user_operations", :force => true do |t|
    t.column "user_id",         :integer,  :null => false
    t.column "operation_id",    :integer,  :null => false
    t.column "operation_count", :integer,  :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_user_scores", :force => true do |t|
    t.column "user_id",    :integer,                   :null => false
    t.column "score",      :integer,  :default => 100, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_user_tags", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "ask_user_tags", ["id"], :name => "index_user_tag_id", :unique => true
  add_index "ask_user_tags", ["name"], :name => "index_user_tag_name"

  create_table "ask_user_uploads", :force => true do |t|
    t.column "type_id",      :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "flag",         :integer,  :default => 0
    t.column "user_id",      :integer
    t.column "ip",           :string
    t.column "path",         :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "album_id",     :integer
  end

  create_table "ask_wiki_catalogs", :force => true do |t|
    t.column "content_id",   :integer
    t.column "catalog_name", :string
    t.column "is_delete",    :integer
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_wiki_contents", :force => true do |t|
    t.column "content_name", :string
    t.column "tag",          :string
    t.column "is_delete",    :integer
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_wiki_items", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "content_id",  :integer
    t.column "catalog_id",  :integer
    t.column "is_delete",   :integer
    t.column "editor_id",   :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "ask_zhidao_admins", :force => true do |t|
    t.column "admin_id",   :integer
    t.column "is_delete",  :integer,  :default => 0, :null => false
    t.column "editor_id",  :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "ask_zhidao_editor_topics", :force => true do |t|
    t.column "editor_id",       :integer
    t.column "zhidao_topic_id", :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_zhidao_editor_uploads", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "flag",         :integer,  :default => 0
    t.column "editor_id",    :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "ask_zhidao_topic_post_votes", :force => true do |t|
    t.column "zhidao_topic_post_id", :integer,  :null => false
    t.column "user_id",              :integer,  :null => false
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
  end

  create_table "ask_zhidao_topic_posts", :force => true do |t|
    t.column "zhidao_topic_id", :integer,                              :null => false
    t.column "user_id",         :integer
    t.column "content",         :text
    t.column "vote_counter",    :integer,               :default => 1, :null => false
    t.column "is_delete",       :integer,               :default => 0, :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "method",          :integer,                              :null => false
    t.column "editor_id",       :integer
    t.column "guest_email",     :string
    t.column "ip",              :string
    t.column "guest_name",      :string
    t.column "expert",          :integer,  :limit => 4, :default => 0, :null => false
    t.column "is_best_post",    :integer,  :limit => 4, :default => 0, :null => false
  end

  add_index "ask_zhidao_topic_posts", ["id"], :name => "index_zhidao_topic_post_id", :unique => true
  add_index "ask_zhidao_topic_posts", ["zhidao_topic_id"], :name => "index_zhidao_topic_post_topic_id"
  add_index "ask_zhidao_topic_posts", ["is_delete"], :name => "index_of_is_delete"

